import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../components/button'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World!</h1>
        <Button variant="primary">Fede</Button>
        <Button variant="secondary">Fede</Button>
      </main>
    </div>
  )
}

export default Home
