import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../components/button'
import { Col, Container, Row } from '../components/grid'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World!</h1>
        <Container>
          <Row>
            <Col>
              <Button variant="primary">Fede</Button>
            </Col>
            <Col>
              <Button variant="secondary">Fede</Button>
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  )
}

export default Home
